general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCST21_51'
    repository: 'poisoned-monkey-sap_tst'

