general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCST21_0'
    repository: 'poisoned-monkey-sap_tst'
  gctsExecuteABAPUnitTests:
    host: 'http://gprd.sapds.ru:8000'
    client: '500'
    abapCredentialsId: 'WRGCST21_0'
    repository: 'poisoned-monkey-sap_tst'
  gctsRollBack:
    host: 'http://gprd.sapds.ru:8000'
    client: '500'
    abapCredentialsId: 'WRGCST21_0'
    repository: 'poisoned-monkey-sap_tst'
  abapEnvironmentRunATCCheck:
    abapCredentialsId: 'WRGCST21_0'
    host: 'http://gprd.sapds.ru:8000'
    atcConfig: 'atcconfig.yml'
    dockerPullImage: false
    
    
