general:
  collectTelemetryData: false
  verbose: true
  steps:
    gctsDeploy:
      host: 'https://gprd.sapds.ru:8000'
      client: '500'
      abapCredentialsId: 'gCTS_target'
      repository: 'poisoned-monkey-sap_tst'
