general:
  collectTelemetryData: false
  verbose: true
  steps:
    gctsDeploy:
      host: 'http://gprd.sapds.ru:8000'
      client: '500'
      abapCredentialsId: 'WRGCTS21_5'
      repository: 'poisoned-monkey-sap_tst'
